Repository y-crdt/ypy, pull requests merged in 2022-07, with the labels that each got.

#66 More Transparent Events
  src/lib.rs
  src/y_array.rs
  src/y_map.rs
  src/y_text.rs
  src/y_xml.rs
  tests/test_y_array.py
  tests/test_y_map.py
  tests/test_y_text.py
  y_py.pyi
Labels: bug

#65 YMap Items View
  src/y_map.rs
  tests/test_y_map.py
  y_py.pyi
Labels: enhancement

#72 Update README.md
  README.md
Labels: documentation

#73 After Transaction Update
  src/lib.rs
  src/type_conversions.rs
  src/y_doc.rs
  src/y_transaction.rs
  tests/test_y_doc.py
  y_py.pyi
Labels: enhancement

#75 Wrapper Refactor
  pyproject.toml
  src/shared_types.rs
  src/type_conversions.rs
  src/y_array.rs
  src/y_map.rs
  src/y_text.rs
  tests/test_y_map.py
Labels: enhancement
